# Generated by Django 5.1.7 on 2025-04-07 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_active_category_updated_at_delivery_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Chủ Nhà Hàng'),
        ),
    ]
