# Generated by Django 5.1.7 on 2025-05-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
    ]
