# Generated by Django 5.1.7 on 2025-05-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_restaurant_price_per_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Giá mỗi km'),
        ),
    ]
