# Generated by Django 5.1.7 on 2025-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='No Name', max_length=255, verbose_name='Tên Nhà Hàng'),
        ),
    ]
