# Generated by Django 5.1.7 on 2025-05-17 16:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='-', max_length=255, null=True, verbose_name='image'),
        ),
    ]
