# Generated by Django 5.1.7 on 2025-05-22 04:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
