# Generated by Django 5.1.7 on 2025-05-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('preparing', 'Đang chuẩn bị'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao'), ('canceled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
