"""
Django settings for yumspot project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

from django.template.defaultfilters import title

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(@wlm+n_tu2#gkg8vn+@q0x-w#-rq#c9ss0fgdwijqj#5oe+*m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

AUTH_USER_MODEL = 'store.User'

INSTALLED_APPS = [
	"unfold",  # before django.contrib.admin
	"unfold.contrib.filters",  # optional, if special filters are needed
	"unfold.contrib.forms",  # optional, if special form elements are needed
	"unfold.contrib.inlines",  # optional, if special inlines are needed
	"unfold.contrib.import_export",  # optional, if django-import-export package is used
	"unfold.contrib.guardian",  # optional, if django-guardian package is used
	"unfold.contrib.simple_history",  # optional, if django-simple-history package is used
	"modeltranslation",
	'captcha',
	'multi_captcha_admin',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'store',
	'cloudinary',
	'cloudinary_storage',
	'rest_framework',
	'drf_yasg',
	'oauth2_provider',
]

# Cloudinary settings
import cloudinary

# Configuration
cloudinary.config(
	cloud_name="dmlyjq2ed",
	api_key="183719924986798",
	api_secret="S8g188ncjHMvhIs8Shgr8N82zTQ",  # Click 'View API Keys' above to copy your API secret
	secure=True
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# settings.py

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


# Hàm kiểm tra quyền
def permission_callback(request):
	return request.user.has_perm("store.change_restaurant")  # Kiểm tra quyền trên model Restaurant


UNFOLD = {
	"SITE_HEADER": "Yumspot Admin",
	"SITE_SUBHEADER": "Bảng điều khiển Yumspot",
	"SITE_SYMBOL": "sprint",
	"BORDER_RADIUS": "10px",
	"SHOW_BACK_BUTTON": True,
	"SHOW_VIEW_ON_SITE": True,  # show/hide "View on site" button, default: True
	"DASHBOARD_CALLBACK": "store.admin.dashboard_callback",
	"SIDEBAR": {
		"show_search": True,  # Search in applications and models names
		"show_all_applications": True,  # Dropdown with all applications and models
		"navigation": [
			{
				"title": _("Navigation"),
				"separator": True,  # Top border
				"collapsible": True,  # Collapsible group of links
				"items": [
					{
						"title": _("Thống kê"),
						"icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
						"link": reverse_lazy("admin:index"),
						"permission": lambda request: request.user.is_superuser,
					},
					{
						"title": _("Người dùng"),
						"icon": "people",
						"link": reverse_lazy("admin:store_user_changelist"),
					},
					{
						"title": _("Nhà hàng"),
						"icon": "restaurant",
						"link": reverse_lazy("admin:store_restaurant_changelist"),
					},
					{
						"title": _("Thực phẩm"),
						"icon": "food_bank",
						"link": reverse_lazy("admin:store_food_changelist"),
					},
					{
						"title": _("Danh mục"),
						"icon": "category",
						"link": reverse_lazy("admin:store_category_changelist"),
					},
					{
						"title": _("Menu"),
						"icon": "menu_book",
						"link": reverse_lazy("admin:store_menu_changelist"),
					}
				],
			},
		],
	},

	"TABS": [
		{
			"models": [
				"store.restaurant",  # Ứng dụng: store, Model: Restaurant
			],
			"items": [
				{
					"title": _("Tất cả nhà hàng"),  # Tiêu đề hiển thị
					"link": reverse_lazy("admin:store_restaurant_changelist"),
					# Đường dẫn đến danh sách Restaurant trong Admin
				},
				{
					"title": _("Thêm nhà hàng"),
					"link": reverse_lazy("admin:store_restaurant_add"),
					"permission": permission_callback,
				}
			],
		},
	],
}

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yumspot.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR / 'store' / 'templates']
		,
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'yumspot.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

import pymysql

pymysql.install_as_MySQLdb()

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'yumspot',
		'USER': 'root',
		'PASSWORD': 'Phuc14kute',
		'HOST': 'yumspot.c9ciw0am85u0.ap-southeast-2.rds.amazonaws.com'  # mặc định localhost
	}
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
	)
}

CSRF_TRUSTED_ORIGINS = [
	"https://0d62-14-169-73-56.ngrok-free.app",
	'https://yumspot.online',
	'https://www.yumspot.online',
]

# OAUTH2_PROVIDER = {
# 	'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuth2Backend',
# }

# 'CLIENT_ID': jyt7S9M6k8NssDHoNQNyLgbeFJfi5qnKElHMeJxp
# 'CLIENT_SECRET': RT007jDkJEvDOMeWisC7Q03mTKe5YZIIe8BNfSVj9HyPoLaixMirYDPJ4VTl3bKlenZygkesFO8CDBIicRjLW2UHrLy6MANgjrZ3iRxJSNTMvq2rpzWvIFfnLwOj6CVk
